### ISSUE TITLE
Package Rename and Registry

### ISSUE THREAD

**Issue by rafaelmartinelli** [rafaelmartinelli/FacilityLocationProblems.jl#8]
Rename package to something clearer and try to add it to Julia's Registry. Suggestions below as comments to be voted.

**Comment by rafaelmartinelli** [comment]
1. FacilityLocation.jl

**Comment by rafaelmartinelli** [comment]
2. CapacitatedFacilityLocation.jl

**Comment by rafaelmartinelli** [comment]
3. CFLP.jl

**Comment by rafaelmartinelli** [comment]
4. CapFacilityLocation.jl

**Comment by piancofelipe** [comment]
FacilityLocationSets.jl
